common: &common
  adapter: postgresql
  username: postgres
  encoding: SQL_ASCII
  template: template0
  pool: 5
  timeout: 5000

local: &local
  host: 127.0.0.1

arch_server: &arch_server
  host: 192.168.2.1

# -----------------
# *** DEFAULT ***
# -----------------

development:
  <<: *common
  <<: *local
  database: ss_development

staging:
  <<: *common
  <<: *local
  database: ss_development

production:
  <<: *common
  <<: *local
  database: ss_development

test:
  <<: *common
  <<: *local
  database: ss_test
